version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: "db"
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - bewiseai_default

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - bewiseai_default

volumes:
  pg_data:

networks:
  bewiseai_default:
    external:
      name: bewiseai_default


